# SlickEdit generated file.  Do not edit this file except in designated areas.

# Make command to use for dependencies
MAKE=make
RM=rm
MKDIR=mkdir

# -----Begin user-editable area-----

# -----End user-editable area-----

# If no configuration is specified, "Debug" will be used
ifndef CFG
CFG=Debug
endif

#
# Configuration: Debug
#
ifeq "$(CFG)" "Debug"
OUTDIR=Debug
OUTFILE=$(OUTDIR)/lsuio
CFG_INC=-I../uio_helper/src 
CFG_LIB=/soc_dev/common/uio_helper/libuio_helper.lib 
CFG_OBJ=
COMMON_OBJ=$(OUTDIR)/lsuio.o 
OBJ=$(COMMON_OBJ) $(CFG_OBJ)
ALL_OBJ=$(OUTDIR)/lsuio.o \
	/soc_dev/common/uio_helper/libuio_helper.lib 

COMPILE="$(CROSS_COMPILE)gcc" -c   -g -ggdb -Wall -o "$(OUTDIR)/$(*F).o" $(CFG_INC) $<
LINK="$(CROSS_COMPILE)gcc"  -g -ggdb -Wall -o "$(OUTFILE)" $(ALL_OBJ)
COMPILE_ADA=gnat -g -c -o "$(OUTDIR)/$(*F).o" "$<"
COMPILE_ADB=gnat -g -c -o "$(OUTDIR)/$(*F).o" "$<"
COMPILE_F=gfortran -c -g -o "$(OUTDIR)/$(*F).o" "$<"
COMPILE_F90=gfortran -c -g -o "$(OUTDIR)/$(*F).o" "$<"
COMPILE_D=gdc -c -g -o "$(OUTDIR)/$(*F).o" "$<"

# Pattern rules
$(OUTDIR)/%.o : %.c
	$(COMPILE)

$(OUTDIR)/%.o : %.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : %.d
	$(COMPILE_D)

$(OUTDIR)/%.o : %.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : %.f90
	$(COMPILE_F90)

$(OUTDIR)/%.o : %.f
	$(COMPILE_F)

# Build rules
all: $(OUTFILE)

$(OUTFILE): $(OUTDIR)  $(OBJ)
	$(LINK)

$(OUTDIR):
	$(MKDIR) -p "$(OUTDIR)"

# Rebuild this project
rebuild: cleanall all

# Clean this project
clean:
	$(RM) -f $(OUTFILE)
	$(RM) -f $(OBJ)

# Clean this project and all dependencies
cleanall: clean
endif

#
# Configuration: Release
#
ifeq "$(CFG)" "Release"
OUTDIR=Release
OUTFILE=$(OUTDIR)/lsuio
CFG_INC=-I../uio_helper/src 
CFG_LIB=/soc_dev/common/uio_helper/libuio_helper.lib 
CFG_OBJ=
COMMON_OBJ=$(OUTDIR)/lsuio.o 
OBJ=$(COMMON_OBJ) $(CFG_OBJ)
ALL_OBJ=$(OUTDIR)/lsuio.o \
	/soc_dev/common/uio_helper/libuio_helper.lib 

COMPILE="$(CROSS_COMPILE)gcc" -c   -o "$(OUTDIR)/$(*F).o" $(CFG_INC) $<
LINK="$(CROSS_COMPILE)gcc"  -o "$(OUTFILE)" $(ALL_OBJ)
COMPILE_ADA=gnat -O -c -o "$(OUTDIR)/$(*F).o" "$<"
COMPILE_ADB=gnat -O -c -o "$(OUTDIR)/$(*F).o" "$<"
COMPILE_F=gfortran -O -g -o "$(OUTDIR)/$(*F).o" "$<"
COMPILE_F90=gfortran -O -g -o "$(OUTDIR)/$(*F).o" "$<"
COMPILE_D=gdc -c -g -o "$(OUTDIR)/$(*F).o" "$<"

# Pattern rules
$(OUTDIR)/%.o : %.c
	$(COMPILE)

$(OUTDIR)/%.o : %.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : %.d
	$(COMPILE_D)

$(OUTDIR)/%.o : %.adb
	$(COMPILE_ADB)

$(OUTDIR)/%.o : %.f90
	$(COMPILE_F90)

$(OUTDIR)/%.o : %.f
	$(COMPILE_F)

# Build rules
all: $(OUTFILE)

$(OUTFILE): $(OUTDIR)  $(OBJ)
	$(LINK)

$(OUTDIR):
	$(MKDIR) -p "$(OUTDIR)"

# Rebuild this project
rebuild: cleanall all

# Clean this project
clean:
	$(RM) -f $(OUTFILE)
	$(RM) -f $(OBJ)

# Clean this project and all dependencies
cleanall: clean
endif
